

# MODEL CONFIG

model:
    repo : hf
    api_key: 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
    pretrained_model_name: google/flan-t5-small # can also choose DistilBERT, GPT2 etc...
    temperature: 0.1
    max_output_length: 1000
    do_sample: true